### ISSUE TITLE
Example doesn't compile

### ISSUE THREAD

**Issue by geotre** [yglukhov/ecs#1]
The example code from the readme doesn't compile on Nim 0.18.0
```
Error: unhandled exception: kind(t) == nnkSym
```

From line 20 in variant.nim. `t.kind` is `nnkObjectTy` which is failing the assert.

**Comment by yglukhov** [comment]
Fixed in https://github.com/yglukhov/variant/commit/6ef188056560c4d04990eae44aa80b1fc3aee9ec. Please update `variant` lib.
